# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simgame', '0003_auto_20180328_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lose_skill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='lose_tot_exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='win_skill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='win_tot_exp',
            field=models.IntegerField(default=0),
        ),
    ]
