# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='New', max_length=255),
            preserve_default=False,
        ),
    ]
