# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_register', '0003_auto_20180326_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='losses',
            new_name='num_losses',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='wins',
            new_name='num_wins',
        ),
    ]
