# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-27 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_register', '0004_auto_20180326_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='num_losses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='num_wins',
        ),
    ]
